### PR TITLE
Added map method

### PR DESCRIPTION
**Pull request by luigitrevisi**
Added a method "map" for mapping from the porperties of the objects to the keys of the dictionary.
The default implementation returns a dictionary where keys and values are the same.

### CODE REVIEW

**Comment by elado** [comment]
Can you please add an example and documentation?

**Comment by elado** [comment]
And tests :)

**Comment by elado** [comment]
Added with tests by #13

**Comment by luigitrevisi** [comment]
Great!
Thank you Elad, sorry if I didn't do it before: I have to learn to write
tests :-(

2014-02-11 Elad Ossadon notifications@github.com:

> Closed #6 https://github.com/elado/jastor/pull/6.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/elado/jastor/pull/6
> .

## 

Luigi Trevisi

**Pull request closed without merging**
